image: registry.gitlab.com/certik/ci-images:conda_base

# Test full dependencies when a C compiler is available and used for linking
full:
  stage: build
  script:
    - export PATH="$HOME/conda_root/bin:$PATH"
    - conda install python=3.6 pytest llvmlite
    - pip install antlr4-python3-runtime
    - sudo apt-get update
    - sudo apt-get install -yq --no-install-recommends wget openjdk-9-jre-headless gcc gfortran gcc-multilib cmake make
    - export CLASSPATH="$HOME/antlr-4.7-complete.jar:$CLASSPATH"
    - (cd; wget http://www.antlr.org/download/antlr-4.7-complete.jar)
    - ./build.sh
    - py.test
    - python show_ast.py
    - ./lfort examples/expr2.f90
    - ./a.out
    - ./test_lfort_cmdline
    - ./test_lfort

# Test minimal dependencies needed to get things to run. No gcc or clang
# compilers, just the linker `ld` and the musl C library.
minimal:
  stage: build
  script:
    - export PATH="$HOME/conda_root/bin:$PATH"
    - conda install python=3.6 pytest llvmlite
    - pip install antlr4-python3-runtime
    - sudo apt-get update
    - sudo apt-get install -yq --no-install-recommends wget openjdk-9-jre-headless musl-dev binutils
    - export CLASSPATH="$HOME/antlr-4.7-complete.jar:$CLASSPATH"
    - (cd; wget http://www.antlr.org/download/antlr-4.7-complete.jar)
    - ./build.sh
    - py.test
    - ./lfort --ld-musl examples/expr2.f90
    - ./a.out
