image: Visual Studio 2017
# List of preinstalled software in the image:
# https://www.appveyor.com/docs/windows-images-software/

install:
- call ci\appveyor_install.bat

build_script:
- call ci\build0.bat
- call ci\build1.bat

test_script:
- set CONDA_INSTALL_LOCN=C:\\Miniconda37-x64
- call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
- pytest
